### ISSUE TITLE
Needed to rename pull request twice

### ISSUE THREAD

**Issue by sophianyberg** [sophiakaterina5/write-docker-actions#7]

**Comment by sophianyberg** [comment]
https://github.com/sophiakaterina5/write-docker-actions/pull/6#issuecomment-667727115

**Comment by sophianyberg** [comment]
Dear Learning Lab bot,
I had to do the renaming twice.
First , I saw an expected error message and renamed the title to **External APIs**.
Then I reloaded the page .
**When I reloaded the page , I saw the error message a second time , even though i rename the pull request. **
**Can you suggest an improvement?**
Thanks,
Sophia Nyberg

**Comment by sophianyberg** [comment]
![603B7FB3-E61B-42CC-9311-A9617541EB5C](https://user-images.githubusercontent.com/66897363/89133174-c6177900-d4ce-11ea-9eea-1f2e591ffb10.jpeg)
![3C5D494F-0D63-48F4-90D0-294B746B1F87](https://user-images.githubusercontent.com/66897363/89133177-c879d300-d4ce-11ea-81db-d26567295e6a.jpeg)

**Comment by sophiakaterina5** [comment]
[issue.zip](https://github.com/sophiakaterina5/write-docker-actions/files/5013047/issue.zip)
![603B7FB3-E61B-42CC-9311-A9617541EB5C](https://user-images.githubusercontent.com/66897363/89133416-7df95600-d4d0-11ea-81af-9c990257135d.jpeg)
![3C5D494F-0D63-48F4-90D0-294B746B1F87](https://user-images.githubusercontent.com/66897363/89133417-7fc31980-d4d0-11ea-9704-9b847f8bd674.jpeg)
**ISSUE
NEEDED TO RENAME PULL REQUEST TWICE
DEAR LEARNING LAB BOT,
I HAD TO DO THE RENAMING TWICE.
FIRST SAW AN EXPECTED ERROR AND RENAMED THE TITLE OF THE PULL REQUEST
TO External APIS.
THEN I RELOADED  THE PAGE.
AFTER I RELOADED THE PAGE,
I SAW THE ERROR MESSAGE A SECOND TIME , 
EVEN THOUGH I RENAMED THE PULL REQUEST.
THANKS,
SOPHIA NYBERG**

**Comment by sophianyberg** [comment]
Ok,  I figured it out . i have to write , not paste the title.
